"""Universal async/sync interface to multiple anti-captcha services."""

from unicaptcha._version import __version__
from unicaptcha.adapter import BaseAdapter, Endpoints
from unicaptcha.challenge import (
    BaseChallenge,
    FunCaptchaChallenge,
    GeeTestV3Challenge,
    GeeTestV4Challenge,
    HCaptchaChallenge,
    ImageChallenge,
    RecaptchaV2Challenge,
    RecaptchaV3Challenge,
    TextChallenge,
    TurnstileChallenge,
)
from unicaptcha.client import AsyncSolver, Solver
from unicaptcha.errors import (
    AuthenticationError,
    ClientClosedError,
    EmptySolutionError,
    ErrorKind,
    InsufficientBalanceError,
    InvalidChallengeError,
    InvalidConfigError,
    NetworkError,
    NoSolutionError,
    ProviderError,
    RateLimitError,
    ServiceBusyError,
    TaskTimeoutError,
    UnicaptchaError,
    UnsupportedChallengeError,
)
from unicaptcha.events import TaskEvent, TaskEventKind
from unicaptcha.solution import (
    BaseSolution,
    FunCaptchaSolution,
    GeeTestV3Solution,
    GeeTestV4Solution,
    HCaptchaSolution,
    ImageSolution,
    RecaptchaV2Solution,
    RecaptchaV3Solution,
    TextSolution,
    TurnstileSolution,
)
from unicaptcha.types import (
    NetworkConfig,
    ParsedTask,
    Proxy,
    ProxyKind,
    RetryConfig,
    SecretStr,
    SubmitAccepted,
    TaskRef,
    TaskResult,
    TaskStatus,
    TaskStatusResult,
    TaskTicket,
    TimeConfig,
)

__all__ = [
    "AsyncSolver",
    "AuthenticationError",
    "BaseAdapter",
    "BaseChallenge",
    "BaseSolution",
    "ClientClosedError",
    "EmptySolutionError",
    "Endpoints",
    "ErrorKind",
    "FunCaptchaChallenge",
    "FunCaptchaSolution",
    "GeeTestV3Challenge",
    "GeeTestV3Solution",
    "GeeTestV4Challenge",
    "GeeTestV4Solution",
    "HCaptchaChallenge",
    "HCaptchaSolution",
    "ImageChallenge",
    "ImageSolution",
    "InsufficientBalanceError",
    "InvalidChallengeError",
    "InvalidConfigError",
    "NetworkConfig",
    "NetworkError",
    "NoSolutionError",
    "ParsedTask",
    "ProviderError",
    "Proxy",
    "ProxyKind",
    "RateLimitError",
    "RecaptchaV2Challenge",
    "RecaptchaV2Solution",
    "RecaptchaV3Challenge",
    "RecaptchaV3Solution",
    "RetryConfig",
    "SecretStr",
    "ServiceBusyError",
    "Solver",
    "SubmitAccepted",
    "TaskEvent",
    "TaskEventKind",
    "TaskRef",
    "TaskResult",
    "TaskStatus",
    "TaskStatusResult",
    "TaskTicket",
    "TaskTimeoutError",
    "TextChallenge",
    "TextSolution",
    "TimeConfig",
    "TurnstileChallenge",
    "TurnstileSolution",
    "UnicaptchaError",
    "UnsupportedChallengeError",
    "__version__",
]
