"""Universal async/sync interface to multiple anti-captcha services."""

from unicaptcha._version import __version__
from unicaptcha.errors import (
    AuthenticationError,
    ClientClosedError,
    EmptySolutionError,
    ErrorKind,
    InsufficientBalanceError,
    InvalidChallengeError,
    InvalidConfigError,
    NetworkError,
    NoSolutionError,
    ProviderError,
    RateLimitError,
    ServiceBusyError,
    TaskTimeoutError,
    UnicaptchaError,
    UnsupportedChallengeError,
)
from unicaptcha.events import TaskEvent, TaskEventKind
from unicaptcha.solution.base import BaseSolution
from unicaptcha.types import (
    NetworkConfig,
    ParsedTask,
    Proxy,
    ProxyKind,
    RetryConfig,
    SecretStr,
    SubmitAccepted,
    TaskRef,
    TaskResult,
    TaskStatus,
    TaskStatusResult,
    TaskTicket,
    TimeConfig,
)

__all__ = [
    "AuthenticationError",
    "BaseSolution",
    "ClientClosedError",
    "EmptySolutionError",
    "ErrorKind",
    "InsufficientBalanceError",
    "InvalidChallengeError",
    "InvalidConfigError",
    "NetworkConfig",
    "NetworkError",
    "NoSolutionError",
    "ParsedTask",
    "ProviderError",
    "Proxy",
    "ProxyKind",
    "RateLimitError",
    "RetryConfig",
    "SecretStr",
    "ServiceBusyError",
    "SubmitAccepted",
    "TaskEvent",
    "TaskEventKind",
    "TaskRef",
    "TaskResult",
    "TaskStatus",
    "TaskStatusResult",
    "TaskTicket",
    "TaskTimeoutError",
    "TimeConfig",
    "UnicaptchaError",
    "UnsupportedChallengeError",
    "__version__",
]
